"""Initial migration

Revision ID: 3ef68871d327
Revises: 
Create Date: 2025-12-18 12:34:24.035447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef68871d327'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'games' not in inspector.get_table_names():
        op.create_table('games',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('player1_id', sa.UUID(), nullable=False),
        sa.Column('player2_id', sa.UUID(), nullable=True),
        sa.Column('winner_id', sa.UUID(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('final_board_state', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('finished_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
