"""Initial migration with game_speed columns

Revision ID: 52848d706ff2
Revises: 
Create Date: 2025-12-18 08:32:13.233997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52848d706ff2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_speed', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('min_elo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_elo', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_queue', schema=None) as batch_op:
        batch_op.drop_column('max_elo')
        batch_op.drop_column('min_elo')
        batch_op.drop_column('game_speed')

    # ### end Alembic commands ###
