"""Initial migration

Revision ID: 6b739be6a8c5
Revises: 
Create Date: 2025-12-18 12:33:50.951458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b739be6a8c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'match_queue' not in inspector.get_table_names():
        op.create_table('match_queue',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('elo', sa.Integer(), nullable=False),
        sa.Column('game_speed', sa.String(length=20), nullable=True),
        sa.Column('min_elo', sa.Integer(), nullable=True),
        sa.Column('max_elo', sa.Integer(), nullable=True),
        sa.Column('joined_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_queue')
    # ### end Alembic commands ###
