"""Update UserProfile model with frontend fields

Revision ID: d5fcc8d2ac13
Revises: f360da7f8fc7
Create Date: 2025-12-16 11:33:56.386724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5fcc8d2ac13'
down_revision = 'f360da7f8fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('games_played', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_won', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_lost', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_drawn', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('win_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('best_win_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('elo_rating', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_profiles_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profiles_username'), ['username'], unique=False)
        batch_op.drop_column('total_losses')
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')
        batch_op.drop_column('total_wins')
        batch_op.drop_column('total_draws')
        batch_op.drop_column('elo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('elo', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_draws', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_wins', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_losses', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_profiles_username'))
        batch_op.drop_index(batch_op.f('ix_user_profiles_email'))
        batch_op.drop_column('elo_rating')
        batch_op.drop_column('best_win_streak')
        batch_op.drop_column('win_streak')
        batch_op.drop_column('games_drawn')
        batch_op.drop_column('games_lost')
        batch_op.drop_column('games_won')
        batch_op.drop_column('games_played')
        batch_op.drop_column('full_name')
        batch_op.drop_column('email')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
