"""Create user_profiles table

Revision ID: f360da7f8fc7
Revises: 
Create Date: 2025-12-16 11:14:17.335938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f360da7f8fc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'user_profiles' not in inspector.get_table_names():
        op.create_table('user_profiles',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('first_name', sa.String(length=100), nullable=True),
        sa.Column('last_name', sa.String(length=100), nullable=True),
        sa.Column('total_wins', sa.Integer(), nullable=True),
        sa.Column('total_losses', sa.Integer(), nullable=True),
        sa.Column('total_draws', sa.Integer(), nullable=True),
        sa.Column('elo', sa.Integer(), nullable=True),
        sa.Column('current_rank', sa.String(length=50), nullable=True),
        sa.Column('last_season_rank', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
